# Generated by Django 4.0.6 on 2022-08-02 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('apellido', 'nombre'),
                'unique_together': {('nombre', 'apellido', 'edad', 'fechaNacimiento')},
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dia_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWebGrupal.empleado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ('dia_de_creacion', '-nombre', 'responsable'),
            },
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('disponible', models.BooleanField()),
                ('responsable_de_uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWebGrupal.empleado')),
                ('tipo_de_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWebGrupal.tareas')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ('nombre', 'tipo_de_tarea', 'responsable_de_uso', 'disponible'),
            },
        ),
    ]
