# Generated by Django 4.0.6 on 2022-08-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebGrupal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramientas',
            options={'ordering': ('nombre', 'disponible', 'tipo_de_tarea'), 'verbose_name': 'Herramienta', 'verbose_name_plural': 'Herramientas'},
        ),
        migrations.RemoveField(
            model_name='herramientas',
            name='responsable_de_uso',
        ),
    ]
