# Generated by Django 4.0.6 on 2022-08-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebGrupal', '0002_alter_herramientas_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('nombre', 'apellido', 'edad')},
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='tipo_de_tarea',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='AppWebGrupal.tareas'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='responsable',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='AppWebGrupal.empleado'),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fechaNacimiento',
        ),
    ]
