# Generated by Django 4.0.6 on 2022-08-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebGrupal', '0003_alter_empleado_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Empleados',
        ),
    ]
