# Generated by Django 4.0.6 on 2022-08-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebGrupal', '0004_rename_empleado_empleados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramientas',
            options={'ordering': ('nombre', 'disponible'), 'verbose_name': 'Herramienta', 'verbose_name_plural': 'Herramientas'},
        ),
        migrations.AlterField(
            model_name='tareas',
            name='dia_de_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='empleados',
            unique_together={('apellido', 'nombre', 'edad')},
        ),
    ]
